import {
  emailHandler,
  type InboundEmailMessage,
} from "./src/email-handler";

// Generated by `opennextjs-cloudflare build` — must exist before `wrangler deploy`.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const handler = require("./.open-next/worker.js") as {
  fetch: (request: Request, env: unknown, ctx: ExecutionContext) => Promise<Response>;
};

type WorkerHandlerEnv = {
  ANTHROPIC_API_KEY?: string;
  HYPERDRIVE?: { connectionString?: string };
};

export default {
  fetch: handler.fetch.bind(handler),

  async email(
    message: InboundEmailMessage,
    env: WorkerHandlerEnv,
    _ctx: unknown,
  ): Promise<void> {
    await emailHandler(message, env);
  },
};
